// <auto-generated />
using System;
using DeclarationManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeclarationManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317085607_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeclarationManagement.Api.Entities.Declaration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicantUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApprovalDocumentName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("AwardLevel")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentNode")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ParticipationType")
                        .HasColumnType("int");

                    b.Property<string>("PrincipalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProjectCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectLevel")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SealUnitAndDate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectCategoryId");

                    b.HasIndex("TaskId");

                    b.ToTable("Declarations", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeclarationId")
                        .HasColumnType("bigint");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UploadedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("DeclarationAttachments", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationFlowLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeclarationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperatorUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("OperatorUserId");

                    b.ToTable("DeclarationFlowLogs", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationReviewRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeclarationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("RecognizedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecognizedAwardLevel")
                        .HasColumnType("int");

                    b.Property<int?>("RecognizedProjectLevel")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReviewAction")
                        .HasColumnType("int");

                    b.Property<int>("ReviewStage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("DeclarationReviewRecords", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("DeclarationTasks", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.ProjectCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProjectCategories", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.UserInitialReviewCategory", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProjectCategoryId");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("UserInitialReviewCategories", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.UserPreReviewDepartment", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("UserPreReviewDepartments", (string)null);
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.Declaration", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.User", "ApplicantUser")
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.Department", "Department")
                        .WithMany("Declarations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.ProjectCategory", "ProjectCategory")
                        .WithMany("Declarations")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.DeclarationTask", "Task")
                        .WithMany("Declarations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicantUser");

                    b.Navigation("Department");

                    b.Navigation("ProjectCategory");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationAttachment", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.Declaration", "Declaration")
                        .WithMany("Attachments")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationFlowLog", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.Declaration", "Declaration")
                        .WithMany("FlowLogs")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.User", "OperatorUser")
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");

                    b.Navigation("OperatorUser");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationReviewRecord", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.Declaration", "Declaration")
                        .WithMany("ReviewRecords")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationTask", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.User", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.UserInitialReviewCategory", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.ProjectCategory", "ProjectCategory")
                        .WithMany("UserInitialReviewCategories")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.User", "User")
                        .WithMany("UserInitialReviewCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.UserPreReviewDepartment", b =>
                {
                    b.HasOne("DeclarationManagement.Api.Entities.Department", "Department")
                        .WithMany("UserPreReviewDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeclarationManagement.Api.Entities.User", "User")
                        .WithMany("UserPreReviewDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.Declaration", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("FlowLogs");

                    b.Navigation("ReviewRecords");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.DeclarationTask", b =>
                {
                    b.Navigation("Declarations");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.Department", b =>
                {
                    b.Navigation("Declarations");

                    b.Navigation("UserPreReviewDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.ProjectCategory", b =>
                {
                    b.Navigation("Declarations");

                    b.Navigation("UserInitialReviewCategories");
                });

            modelBuilder.Entity("DeclarationManagement.Api.Entities.User", b =>
                {
                    b.Navigation("UserInitialReviewCategories");

                    b.Navigation("UserPreReviewDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
